name: REUSE

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: REUSE compliance
        uses: fsfe/reuse-action@676e2d560c9a403aa252096d99fcab3e1132b0f5 # v6.0.0
